name: palm_api_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0
environment:
  sdk: '>=3.0.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.0.0
  json_annotation: ^4.8.1
  flutter_markdown: ^0.6.14
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.0
  json_serializable: ^6.7.0
flutter:
  uses-material-design: true
